<?php
declare(strict_types=1);

return [
    ['id'=>'profile','type'=>'profile','slug'=>'profile','title'=>'Profile','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Cagatin Mark Jed','role'=>'Full-Stack Developer','location'=>'Metro Manila, Philippines','availability'=>'Open to collaborations',
        'intro'=>'I build clear and dependable systems for real-world needs.','biography'=>'I am a developer focused on practical systems, understandable interfaces, and continuous learning. This portfolio documents my work, activities, resume, and reflections.','skills'=>['PHP','Python','MySQL','JavaScript','System Design']]],
    ['id'=>'system','type'=>'current_system','slug'=>'current-system','title'=>'Current System','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Community Service Management System','summary'=>'A simple workspace for resident requests and staff review.','description'=>'The system organizes requests, document verification, status tracking, and reporting in one clear workflow.','status'=>'In development','progress'=>68,'technologies'=>['Native PHP','MySQL','JavaScript','Tailwind CSS'],'current_focus'=>'Improving document review and status tracking.','next_milestone'=>'Complete usability testing.']],
    ['id'=>'project-1','type'=>'project','slug'=>'service-hub','title'=>'Service Hub','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Service Hub','slug'=>'service-hub','summary'=>'A request-management portal for community services.','description'=>'Residents submit requests while staff review information and update progress through a straightforward workflow.','status'=>'In development','year'=>'2026','technologies'=>['Native PHP','MySQL','JavaScript'],'highlights'=>['Owner-managed content','Clear status tracking','Responsive pages']]],
    ['id'=>'activity-1','type'=>'activity','slug'=>'interface-prototyping','title'=>'Interface Prototyping Workshop','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Interface Prototyping Workshop','slug'=>'interface-prototyping','date'=>'2026-07-18','category'=>'Workshop','summary'=>'Converted a paper workflow into a simple prototype.','description'=>'I mapped each task, removed repeated steps, and tested a clearer interface.','outcomes'=>['Improved information hierarchy','Practiced workflow mapping','Recorded user feedback']]],
    ['id'=>'reflection-1','type'=>'reflection','slug'=>'designing-with-evidence','title'=>'Designing with Evidence','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Designing with Evidence','slug'=>'designing-with-evidence','date'=>'2026-07-20','course'=>'Systems Analysis and Design','instructor'=>'Sample Instructor','activity'=>'Interface Prototyping Workshop','experience'=>'I converted a multi-step workflow into an interactive prototype.','observations'=>'Users depended on familiar wording and visible progress.','learning'=>'I learned to test design decisions instead of treating them as final answers.','next_steps'=>'Test important workflows earlier and document each revision.','conclusion'=>'Useful systems grow through observation, iteration, and respect for users.']],
    ['id'=>'resume','type'=>'resume','slug'=>'resume','title'=>'Resume','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Cagatin Mark Jed','headline'=>'Full-Stack Developer','email'=>'alex@example.com','phone'=>'+63 900 000 0000','location'=>'Metro Manila, Philippines','website'=>'portfolio.example.com','summary'=>'Developer focused on accessible interfaces and dependable systems.','experience'=>[['role'=>'Full-Stack Developer','organization'=>'Independent Projects','period'=>'2025 — Present','details'=>['Developed full-stack applications from requirements to deployment.','Built responsive interfaces and maintainable data models.']]],'education'=>[['degree'=>'BS Information Technology','school'=>'Sample University','period'=>'2022 — 2026','details'=>'Software engineering, databases, networking, and systems analysis.']],'skills'=>[['group'=>'Development','items'=>['PHP','Python','JavaScript','Tailwind CSS']],['group'=>'Data','items'=>['MySQL','PDO','Git']]]]],
    ['id'=>'contact','type'=>'contact','slug'=>'contact','title'=>'Contact','sort_order'=>0,'is_published'=>1,'data'=>[
        'email'=>'alex@example.com','message'=>'Have a project or opportunity worth discussing? Send me an email.','links'=>[['label'=>'GitHub','url'=>'https://github.com/'],['label'=>'LinkedIn','url'=>'https://linkedin.com/']]]],
];
