<?php
declare(strict_types=1);

return [
    ['id'=>'profile','type'=>'profile','slug'=>'profile','title'=>'Profile','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Cagatin Mark Jed','full_name'=>'Mark Jed M. Cagatin','role'=>'Student Developer','location'=>'Fatima, San Miguel, Zamboanga del Sur','availability'=>'Open to collaborations','age'=>'21','birthdate'=>'March 11, 2005','school'=>'JH Cerilles State College','course_year'=>'Bachelor of Information Technology — 4th Year','dream_job'=>'Developer',
        'intro'=>'I am a student developer committed to improving my skills and building better solutions through consistent practice.','biography'=>'I continuously learn, explore new technologies, and strengthen how I design and develop practical systems. Every project and activity is an opportunity to grow, learn from challenges, and become a better developer.','skills'=>['HTML','CSS','PHP','JavaScript','MySQL','Python','Git','Flutter','Dart','REST APIs','Responsive Web Design','System Design']]],
    ['id'=>'system','type'=>'current_system','slug'=>'current-system','title'=>'Current System','sort_order'=>0,'is_published'=>1,'data'=>[
        'name'=>'Community Service Management System','summary'=>'A simple workspace for resident requests and staff review.','description'=>'The system organizes requests, document verification, status tracking, and reporting in one clear workflow.','status'=>'In development','progress'=>68,'technologies'=>['Native PHP','MySQL','JavaScript','Tailwind CSS'],'current_focus'=>'Improving document review and status tracking.','next_milestone'=>'Complete usability testing.']],
    ['id'=>'project-1','type'=>'project','slug'=>'service-hub','title'=>'Service Hub','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Service Hub','slug'=>'service-hub','summary'=>'A request-management portal for community services.','description'=>'Residents submit requests while staff review information and update progress through a straightforward workflow.','status'=>'In development','year'=>'2026','technologies'=>['Native PHP','MySQL','JavaScript'],'highlights'=>['Owner-managed content','Clear status tracking','Responsive pages']]],
    ['id'=>'activity-1','type'=>'activity','slug'=>'interface-prototyping','title'=>'Interface Prototyping Workshop','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Interface Prototyping Workshop','slug'=>'interface-prototyping','date'=>'2026-07-18','category'=>'Workshop','summary'=>'Converted a paper workflow into a simple prototype.','description'=>'I mapped each task, removed repeated steps, and tested a clearer interface.','outcomes'=>['Improved information hierarchy','Practiced workflow mapping','Recorded user feedback']]],
    ['id'=>'reflection-1','type'=>'reflection','slug'=>'designing-with-evidence','title'=>'Designing with Evidence','sort_order'=>0,'is_published'=>1,'data'=>[
        'title'=>'Designing with Evidence','slug'=>'designing-with-evidence','date'=>'2026-07-20','course'=>'Systems Analysis and Design','instructor'=>'Sample Instructor','activity'=>'Interface Prototyping Workshop','experience'=>'I converted a multi-step workflow into an interactive prototype.','observations'=>'Users depended on familiar wording and visible progress.','learning'=>'I learned to test design decisions instead of treating them as final answers.','next_steps'=>'Test important workflows earlier and document each revision.','conclusion'=>'Useful systems grow through observation, iteration, and respect for users.']],
    ['id'=>'resume','type'=>'resume','slug'=>'resume','title'=>'Resume','sort_order'=>0,'is_published'=>1,'data'=>[
        'resume_version'=>2,'name'=>'MARK JED M CAGATIN','headline'=>'WEB DEVELOPER | BSIT STUDENT','location'=>'San Miguel, Zamboanga del Sur','phone'=>'+63 9187439096','email'=>'cagatinmark26@gmail.com','github'=>'github.com/yukino123-bee','linkedin'=>'https://www.linkedin.com/in/mark-cagatin/','website'=>'Portfolio','summary'=>'BSIT student and aspiring web developer with hands-on experience building database-driven web applications. Skilled in front-end and back-end development, relational databases, Git-based workflows, and Linux development environments. Seeking an internship or entry-level role where practical development and problem-solving skills can contribute to real projects.','skills'=>[['group'=>'Languages','items'=>['PHP','JavaScript','Python','HTML','CSS']],['group'=>'Frameworks','items'=>['Laravel','Bootstrap']],['group'=>'Databases','items'=>['MySQL','SQLite']],['group'=>'Tools & Platforms','items'=>['Git','GitHub','VS Code','Linux/Fedora','Apache','Ollama']]],'projects'=>[['name'=>'GovAssist','technologies'=>'Laravel, PHP, MySQL, JavaScript, Bootstrap','description'=>'Developed a web-based local government service assistance and eligibility assessment system with resident/staff workflows, eligibility screening, document submission and validation, OCR-assisted verification, application tracking, and reporting.'],['name'=>'Project Name','technologies'=>'Technology Stack','description'=>'Replace this line with one concise statement describing what you built, your technical contribution, and the most important result or feature.']],'education_degree'=>'Bachelor of Science in Information Technology','education_period'=>'Expected Graduation: 2027','education_school'=>'JH Cerilles State College, Mati San Miguel, Zamboanga del Sur','activity_role'=>'Role / Internship / Hackathon / Organization','activity_organization'=>'Organization','activity_year'=>'Year','activity_details'=>'Add one concise achievement or responsibility. Remove this section if you have no relevant experience yet.','certifications'=>'Certification / Award — Issuer, Year | Certification / Award — Issuer, Year']],
    ['id'=>'contact','type'=>'contact','slug'=>'contact','title'=>'Contact','sort_order'=>0,'is_published'=>1,'data'=>[
        'email'=>'cagatinmark26@gmail.com','message'=>'Have a project or opportunity worth discussing? Send me an email.','links'=>[['label'=>'Facebook','url'=>'https://www.facebook.com/mark.jed.cagatin.2025/'],['label'=>'GitHub','url'=>'https://github.com/yukino123-bee'],['label'=>'LinkedIn','url'=>'https://www.linkedin.com/in/mark-cagatin-9a868a392/']]]],
];
