<?php
declare(strict_types=1);

function e(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function tags(array $items): void { echo '<div class="flex flex-wrap gap-2">'; foreach ($items as $item) echo '<span class="tag">'.e($item).'</span>'; echo '</div>'; }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(ucfirst(str_replace('_',' ',$page)))?> — Portfolio</title><meta name="description" content="Developer portfolio, current systems, projects, activities, resume, and reflections."><script>try{const saved=localStorage.getItem('portfolio-theme');document.documentElement.dataset.theme=saved||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light')}catch(error){}</script><style>html{background:#fff}html[data-theme="dark"]{background:#101112}</style><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/style.css"></head><body class="page-<?=e($page)?> bg-white text-black antialiased">
<aside class="sidebar no-print"><a href="/" class="sidebar-name"><?=e($profile['name']??'Cagatin Mark Jed')?></a><button id="menu-button" class="sidebar-menu-button" aria-expanded="false" aria-controls="mobile-menu">Menu</button><nav id="mobile-menu" class="sidebar-nav hidden"><a href="/" class="<?=$page==='home'?'active':''?>">Home</a><details class="sidebar-dropdown" <?=in_array($page,['activities','activity','reflections','reflection','resume'],true)?'open':''?>><summary class="<?=in_array($page,['activities','activity','reflections','reflection','resume'],true)?'active':''?>">Activities <span aria-hidden="true">⌄</span></summary><div class="sidebar-submenu"><a href="/?page=reflections" class="<?=in_array($page,['reflections','reflection'],true)?'active':''?>">Reflections</a><a href="/?page=resume" class="<?=$page==='resume'?'active':''?>">Resume</a></div></details><?php if(owner_logged_in()):?><a href="/?page=admin">Edit portfolio</a><?php endif;?></nav><div class="active-viewers" aria-live="polite"><span class="active-viewers-dot" aria-hidden="true"></span><span><strong id="active-view-count">—</strong> active now</span></div></aside>
<main class="app-main">
<?php if($page==='home'):?>
<?php
$contactLinks=[];
foreach($contact['links']??[] as $link){$contactLinks[strtolower($link['label']??'')]=$link['url']??'';}
$profileSocials=[
    'facebook'=>$contactLinks['facebook']??'https://www.facebook.com/mark.jed.cagatin.2025/',
    'github'=>$contactLinks['github']??'https://github.com/yukino123-bee',
    'linkedin'=>$contactLinks['linkedin']??'https://www.linkedin.com/in/mark-cagatin-9a868a392/',
    'email'=>'mailto:'.($contact['email']??'cagatinmark26@gmail.com'),
];
?>
<section class="hero-texture"><div class="site-width landing-profile py-20"><div class="profile-portrait"><div class="profile-photo"><img src="/assets/profile-photo.png" alt="Portrait of Cagatin Mark Jed"></div><nav class="profile-socials" aria-label="Social links"><?php foreach($profileSocials as $label=>$url):?><a href="<?=e($url)?>" target="_blank" rel="noreferrer" aria-label="<?=e($label)?>"><?=e($label)?><span aria-hidden="true">↗</span></a><?php endforeach;?></nav></div><div class="profile-intro"><p class="label"><?=e($profile['role']??'Full-Stack Developer')?></p><div class="profile-name-wrap mt-4"><h1><button id="profile-name-button" class="profile-name-button text-5xl font-semibold tracking-[-.05em]" type="button" aria-expanded="false" aria-controls="profile-full-info"><?=e($profile['name']??'Cagatin Mark Jed')?></button></h1><span class="name-tap-cursor" aria-hidden="true">☝</span></div><div id="profile-full-info" class="profile-full-info" hidden><p class="label">Full information</p><dl><div><dt>Name</dt><dd><?=e($profile['full_name']??'Mark Jed M. Cagatin')?></dd></div><div><dt>Age</dt><dd><?=e($profile['age']??'21')?></dd></div><div><dt>Birthdate</dt><dd><?=e($profile['birthdate']??'March 11, 2005')?></dd></div><div><dt>School</dt><dd><?=e($profile['school']??'JH Cerilles State College')?></dd></div><div><dt>Course &amp; Year</dt><dd><?=e($profile['course_year']??'Bachelor of Information Technology — 4th Year')?></dd></div><div><dt>Dream Job</dt><dd><?=e($profile['dream_job']??'Developer')?></dd></div></dl></div><p class="mt-5 max-w-xl text-lg text-neutral-600"><?=e($profile['intro']??'')?></p><p class="mt-3 max-w-xl text-neutral-600"><?=e($profile['biography']??'')?></p><div class="profile-meta"><span><?=e($profile['location']??'Metro Manila, Philippines')?></span><span><?=e($profile['availability']??'Open to collaborations')?></span></div><div class="mt-6"><?php tags($profile['skills']??[]);?></div></div><article class="current-work"><div class="section-heading"><span>01</span><p class="label">Currently building</p></div><p class="current-work-placeholder">Coming soon</p></article></div></section>
<?php elseif($page==='about'):?>
<?php page_head('About','Curious by nature. Deliberate in practice.',$profile['biography']??'');?><section class="site-width grid gap-10 py-16 md:grid-cols-[1fr_320px]"><div><h2 class="text-3xl font-semibold">Current system</h2><h3 class="mt-6 text-2xl"><?=e($system['name']??'')?></h3><p class="mt-3 text-neutral-600"><?=e($system['description']??'')?></p><p class="mt-6"><strong>Current focus:</strong> <?=e($system['current_focus']??'')?></p><p><strong>Next milestone:</strong> <?=e($system['next_milestone']??'')?></p></div><aside class="panel"><p class="label">Skills</p><div class="mt-5"><?php tags($profile['skills']??[]);?></div></aside></section>
<?php elseif($page==='activities'):?>
<?php page_head('Activities','Activities that sharpen the work.','A clear record of the work, the process, and the lessons that followed.');?><section class="site-width grid gap-5 py-16 md:grid-cols-2"><?php foreach($items as $item):$d=$item['data'];?><a class="panel" href="/?page=activity&slug=<?=e($item['slug'])?>"><p class="label"><?=e($d['date']??$d['category']??'')?></p><h2 class="mt-4 text-2xl font-semibold"><?=e($d['title']??$item['title'])?></h2><p class="mt-3 text-neutral-600"><?=e($d['summary']??'')?></p><span class="mt-6 inline-block font-semibold">Read →</span></a><?php endforeach;?></section>
<?php elseif($page==='activity'): if(!$item):http_response_code(404);echo '<div class="site-width py-20"><h1>Not found</h1></div>';else:$d=$item['data'];?>
<?php page_head(ucfirst($page),$d['title']??$item['title'],$d['summary']??'');?><article class="site-width max-w-3xl py-16"><p class="text-lg text-neutral-700"><?=nl2br(e($d['description']??''))?></p><?php $list=$d['highlights']??$d['outcomes']??[];if($list):?><h2 class="mt-10 text-2xl font-semibold">Highlights</h2><ul class="mt-4 list-disc space-y-2 pl-6"><?php foreach($list as $line):?><li><?=e($line)?></li><?php endforeach;?></ul><?php endif;?></article><?php endif;?>
<?php elseif($page==='resume'): $d=$item['data']??[];?>
<section class="site-width py-10"><div class="no-print mb-5 flex items-center justify-between"><div><p class="label">A4 document</p><h1 class="mt-2 text-3xl font-semibold">Resume</h1></div><?php if(!empty($d['uploaded_pdf'])):?><a class="button" href="<?=e($d['uploaded_pdf'])?>" target="_blank" rel="noreferrer">Open / Print PDF</a><?php else:?><button onclick="window.print()" class="button">Print / Save PDF</button><?php endif;?></div><?php if(!empty($d['uploaded_pdf'])):?><div class="imported-pdf-shell"><iframe src="<?=e($d['uploaded_pdf'])?>" title="Imported resume PDF"></iframe><a class="button-outline no-print" href="<?=e($d['uploaded_pdf'])?>" download="<?=e($d['uploaded_pdf_name']??'resume.pdf')?>">Download PDF</a></div><?php else:?><div class="paper-shell"><article class="paper <?=e($layout['resume_template'])?>" style="--doc-size:<?=e($layout['font_size'])?>pt;--doc-line:<?=e($layout['line_height'])?>;--doc-space:<?=e($layout['section_spacing'])?>px;font-family:<?=e($layout['font_family'])?>,Arial,sans-serif"><header class="text-center border-b-2 border-black pb-4"><h1 class="text-4xl font-bold"><?=e($d['name']??'')?></h1><p class="font-semibold"><?=e($d['headline']??'')?></p><p class="text-sm text-neutral-600"><?=e(($d['email']??'').' · '.($d['phone']??'').' · '.($d['location']??''))?></p></header><?php doc_section('Summary','<p>'.e($d['summary']??'').'</p>');doc_entries('Experience',$d['experience']??[],'role','organization');doc_entries('Education',$d['education']??[],'degree','school');?><section class="doc-section"><h2>Skills</h2><?php foreach($d['skills']??[] as $s):?><p><strong><?=e($s['group']??'')?>:</strong> <?=e(implode(' · ',$s['items']??[]))?></p><?php endforeach;?></section></article></div><?php endif;?></section>
<?php elseif($page==='reflection'): if(!$item):http_response_code(404);echo 'Not found';else:$d=$item['data']?>
<section class="site-width py-10"><div class="no-print mb-5 flex items-center justify-between"><div><p class="label">A4 document</p><h1 class="mt-2 text-3xl font-semibold">Reflection</h1></div><?php if(!empty($d['uploaded_pdf'])):?><a class="button" href="<?=e($d['uploaded_pdf'])?>" target="_blank" rel="noreferrer">Open / Print PDF</a><?php else:?><button onclick="window.print()" class="button">Print / Save PDF</button><?php endif;?></div><?php if(!empty($d['uploaded_pdf'])):?><div class="imported-pdf-shell"><iframe src="<?=e($d['uploaded_pdf'])?>" title="Imported reflection PDF"></iframe><a class="button-outline no-print" href="<?=e($d['uploaded_pdf'])?>" download="<?=e($d['uploaded_pdf_name']??'reflection.pdf')?>">Download PDF</a></div><?php else:?><div class="paper-shell"><article class="paper reflection <?=e($layout['reflection_template'])?>" style="--doc-size:<?=e($layout['font_size'])?>pt;--doc-line:<?=e($layout['line_height'])?>;--doc-space:<?=e($layout['section_spacing'])?>px;font-family:<?=e($layout['font_family'])?>,Arial,sans-serif"><header class="reflection-document-header border-b-2 border-black pb-4"><h1 class="text-4xl font-bold"><?=e($profile['name']??'Cagatin Mark Jed')?></h1><p class="font-semibold"><?=e($d['title']??'Reflection Paper')?></p><p class="text-sm text-neutral-600"><?=e(($d['course']??'').' · '.($d['instructor']??'').' · '.($d['date']??''))?></p></header><?php if(!empty($d['activity']))doc_section('Activity','<p>'.e($d['activity']).'</p>');foreach(['Experience'=>'experience','Observations'=>'observations','Learning'=>'learning','Next Steps'=>'next_steps','Conclusion'=>'conclusion'] as $label=>$key)doc_section($label,'<p>'.e($d[$key]??'').'</p>');?></article></div><?php endif;?></section><?php endif;?>
<?php elseif($page==='login'):?><section class="site-width flex min-h-[70vh] items-center justify-center py-16"><form method="post" class="panel w-full max-w-md"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="login"><p class="label">Owner access</p><h1 class="mt-4 text-3xl font-semibold">Sign in</h1><?php if($error):?><p class="mt-4 border border-neutral-400 bg-neutral-100 p-3"><?=e($error)?></p><?php endif;?><label class="mt-6 block text-sm font-semibold">Email<input class="field" name="email" type="email" required></label><label class="mt-4 block text-sm font-semibold">Password<input class="field" name="password" type="password" required></label><button class="button mt-6 w-full">Sign in</button></form></section>
<?php elseif($page==='admin'):require_owner();?><?php page_head('Admin','Portfolio content','Edit drafts and publish only when the content is ready.');?><section class="site-width admin-dashboard py-12"><?php if($error):?><p class="admin-alert"><?=e($error)?></p><?php endif;?><div class="admin-toolbar"><div class="admin-toolbar-actions"><a class="button-outline" href="/?page=layouts">Paper templates</a><?php foreach(['activity','reflection'] as $newType):?><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="create"><input type="hidden" name="type" value="<?=$newType?>"><button class="button-outline">New <?=e($newType)?></button></form><?php endforeach;?></div><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="logout"><button class="admin-signout">Sign out</button></form></div><div class="admin-summary"><div><strong><?=count($items)?></strong><span>Total entries</span></div><div><strong><?=count(array_filter($items,fn($entry)=>!empty($entry['is_published'])))?></strong><span>Published</span></div><div><strong><?=count(array_filter($items,fn($entry)=>empty($entry['is_published'])))?></strong><span>Drafts</span></div></div><div class="admin-content-grid"><?php foreach($items as $item):?><article class="admin-content-card"><div class="admin-card-top"><span class="admin-type"><?=e(str_replace('_',' ',$item['type']))?></span><span class="admin-status <?=$item['is_published']?'is-published':'is-draft'?>"><?=$item['is_published']?'Published':'Draft'?></span></div><h2><?=e($item['title'])?></h2><?php if(in_array($item['type'],['resume','reflection'],true)):?><form class="pdf-import-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="upload_pdf"><input type="hidden" name="id" value="<?=e($item['id'])?>"><label><span>Import PDF</span><input name="pdf" type="file" accept="application/pdf,.pdf" required></label><button>Upload</button></form><?php endif;?><div class="admin-card-footer"><span>Content entry</span><a href="/?page=edit&id=<?=e($item['id'])?>">Edit <span aria-hidden="true">→</span></a></div></article><?php endforeach;?></div></section>
<?php elseif($page==='edit'):require_owner();if(!$item):echo 'Not found';else:$d=$item['data'];?>
<section class="site-width document-edit-page py-12"><a href="/?page=admin">← Admin</a><h1 class="mt-5 text-3xl font-semibold">Edit <?=e($item['title'])?></h1><?php if($error):?><p class="mt-4 bg-neutral-100 p-3"><?=e($error)?></p><?php endif;?><form method="post" class="mt-8 space-y-5"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="id" value="<?=e($item['id'])?>"><?php if($item['type']==='profile'):?><input type="hidden" name="profile_form" value="1"><input type="hidden" name="title" value="<?=e($item['title'])?>"><input type="hidden" name="slug" value="<?=e($item['slug'])?>"><input type="hidden" name="sort_order" value="<?=e($item['sort_order'])?>"><div class="profile-editor-heading"><img src="/assets/profile-photo.png" alt="Current profile photo"><div><p class="label">Current profile</p><h2 class="mt-2 text-2xl font-semibold"><?=e($d['name']??'Cagatin Mark Jed')?></h2></div></div><div class="grid gap-5 md:grid-cols-2"><?php editor_input('name','Display name',$d['name']??'');editor_input('role','Role',$d['role']??'');editor_input('location','Location',$d['location']??'');editor_input('availability','Availability',$d['availability']??'');?></div><div class="profile-editor-section"><p class="label">Expandable full information</p><div class="grid gap-5 md:grid-cols-2"><?php editor_input('full_name','Full name',$d['full_name']??'Mark Jed M. Cagatin');editor_input('age','Age',$d['age']??'21','number');editor_input('birthdate','Birthdate',$d['birthdate']??'March 11, 2005');editor_input('school','School',$d['school']??'JH Cerilles State College');editor_input('course_year','Course & Year',$d['course_year']??'Bachelor of Information Technology — 4th Year');editor_input('dream_job','Dream Job',$d['dream_job']??'Developer');?></div></div><?php editor_textarea('intro','Introduction',$d['intro']??'');editor_textarea('biography','Biography',$d['biography']??'');editor_input('skills','Skills',implode(', ',$d['skills']??[]));?>
<?php elseif($item['type']==='resume'):?><input type="hidden" name="resume_form" value="1"><input type="hidden" name="title" value="<?=e($item['title'])?>"><input type="hidden" name="slug" value="<?=e($item['slug'])?>"><input type="hidden" name="sort_order" value="<?=e($item['sort_order'])?>"><div class="document-editor-shell"><div class="document-editor-paper"><header class="document-editor-header"><?php editor_input('name','Full name',$d['name']??'');editor_input('headline','Professional headline',$d['headline']??'');?><div class="document-editor-contact"><?php editor_input('email','Email',$d['email']??'','email');editor_input('phone','Phone',$d['phone']??'');editor_input('location','Location',$d['location']??'');editor_input('website','Website',$d['website']??'');?></div></header><section class="document-editor-section"><h2>Summary</h2><?php editor_textarea('summary','Professional summary',$d['summary']??'');?></section><section class="document-editor-section"><h2>Experience</h2><?php foreach($d['experience']??[] as $entry):?><div class="document-editor-entry"><div class="document-editor-row"><?php editor_input('experience_role[]','Role',$entry['role']??'');editor_input('experience_organization[]','Organization',$entry['organization']??'');editor_input('experience_period[]','Period',$entry['period']??'');?></div><?php editor_textarea('experience_details[]','Details — one point per line',is_array($entry['details']??null)?implode("\n",$entry['details']):($entry['details']??''));?></div><?php endforeach;?></section><section class="document-editor-section"><h2>Education</h2><?php foreach($d['education']??[] as $entry):?><div class="document-editor-entry"><div class="document-editor-row"><?php editor_input('education_degree[]','Degree',$entry['degree']??'');editor_input('education_school[]','School',$entry['school']??'');editor_input('education_period[]','Period',$entry['period']??'');?></div><?php editor_textarea('education_details[]','Details',is_array($entry['details']??null)?implode("\n",$entry['details']):($entry['details']??''));?></div><?php endforeach;?></section><section class="document-editor-section"><h2>Skills</h2><?php foreach($d['skills']??[] as $skill):?><div class="document-editor-skill"><?php editor_input('skill_group[]','Group',$skill['group']??'');editor_input('skill_items[]','Skills — separated by commas',implode(', ',$skill['items']??[]));?></div><?php endforeach;?></section></div></div>
<?php elseif($item['type']==='reflection'):?><input type="hidden" name="reflection_form" value="1"><input type="hidden" name="slug" value="<?=e($item['slug'])?>"><input type="hidden" name="sort_order" value="<?=e($item['sort_order'])?>"><div class="document-editor-shell"><div class="document-editor-paper"><header class="document-editor-header"><?php editor_input('title','Reflection title',$d['title']??$item['title']);?><div class="document-editor-contact"><?php editor_input('course','Course',$d['course']??'');editor_input('instructor','Instructor',$d['instructor']??'');editor_input('date','Date',$d['date']??'','date');?></div></header><?php foreach(['Activity'=>'activity','Experience'=>'experience','Observations'=>'observations','Learning'=>'learning','Next Steps'=>'next_steps','Conclusion'=>'conclusion'] as $label=>$field):?><section class="document-editor-section"><h2><?=e($label)?></h2><?php editor_textarea($field,$label,$d[$field]??'');?></section><?php endforeach;?></div></div>
<?php else:?><label class="block font-semibold">Title<input class="field" name="title" value="<?=e($item['title'])?>" required></label><label class="block font-semibold">URL slug<input class="field" name="slug" value="<?=e($item['slug'])?>" pattern="[a-z0-9-]+" required></label><label class="block font-semibold">Display order<input class="field" name="sort_order" type="number" value="<?=e($item['sort_order'])?>"></label><label class="block font-semibold">Content data<textarea class="field min-h-96 font-mono text-sm" name="data" required><?=e(json_encode($d,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></textarea></label><?php endif;?><div class="editor-actions"><button class="button-outline" name="action" value="save">Save draft</button><button class="button" name="action" value="publish">Save & publish</button><?php if($item['is_published']):?><button class="button-outline" name="action" value="unpublish">Unpublish</button><?php endif;?><?php if(in_array($item['type'],['project','activity','reflection'],true)):?><button class="button-outline" onclick="return confirm('Delete this item?')" name="action" value="delete">Delete</button><?php endif;?></div></form></section><?php endif;?>
<?php elseif($page==='layouts'):require_owner()?><section class="site-width max-w-3xl py-12"><p class="label">Paper templates only</p><h1 class="mt-4 text-4xl font-semibold">Resume and reflection layout</h1><p class="mt-3 text-neutral-600">A4 size and one-inch margins are fixed and apply only to printed documents.</p><form method="post" class="panel mt-8 grid gap-5 md:grid-cols-2"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="layout"><?php select_field('resume_template','Resume template',['classic'=>'Classic','modern'=>'Modern'],$layout);select_field('reflection_template','Reflection template',['academic'=>'Academic','journal'=>'Journal'],$layout);select_field('font_family','Font',['Arial'=>'Arial','Georgia'=>'Georgia','Inter'=>'Inter'],$layout);number_field('font_size','Font size',8,14,.5,$layout);number_field('line_height','Line height',1.1,2,.05,$layout);number_field('section_spacing','Section spacing',8,32,1,$layout);?><button class="button md:col-span-2">Save layout</button></form></section>
<?php else:http_response_code(404);?><section class="site-width py-24"><h1 class="text-5xl font-semibold">Page not found</h1></section><?php endif;?>
</main><footer class="app-footer no-print border-t border-neutral-200"><div class="site-width flex justify-between py-7 text-sm text-neutral-500"><span>© <?=date('Y')?> <?=e($profile['name']??'Portfolio')?></span><a href="/?page=login">Owner</a></div></footer><script src="/assets/app.js"></script></body></html>
<?php
function page_head(string $label,string $title,string $description):void{echo '<header class="border-b border-neutral-200"><div class="site-width py-16"><p class="label">'.e($label).'</p><h1 class="mt-4 text-5xl font-semibold tracking-[-.04em]">'.e($title).'</h1><p class="mt-5 max-w-3xl text-lg text-neutral-600">'.e($description).'</p></div></header>';}
function doc_section(string $title,string $html):void{echo '<section class="doc-section"><h2>'.e($title).'</h2>'.$html.'</section>';}
function doc_entries(string $title,array $entries,string $primary,string $secondary):void{ob_start();foreach($entries as $entry){echo '<article class="mb-3 break-inside-avoid"><div class="flex justify-between gap-4"><strong>'.e($entry[$primary]??'').' · '.e($entry[$secondary]??'').'</strong><span>'.e($entry['period']??'').'</span></div>';if(isset($entry['details'])&&is_array($entry['details'])){echo '<ul class="list-disc pl-5">';foreach($entry['details'] as $x)echo '<li>'.e($x).'</li>';echo '</ul>';}elseif(isset($entry['details']))echo '<p>'.e($entry['details']).'</p>';echo '</article>';}doc_section($title,ob_get_clean());}
function select_field(string $name,string $label,array $choices,array $data):void{echo '<label class="font-semibold">'.e($label).'<select class="field" name="'.e($name).'">';foreach($choices as $value=>$text)echo '<option value="'.e($value).'" '.(($data[$name]??'')===$value?'selected':'').'>'.e($text).'</option>';echo '</select></label>';}
function number_field(string $name,string $label,float $min,float $max,float $step,array $data):void{echo '<label class="font-semibold">'.e($label).'<input class="field" type="number" name="'.e($name).'" min="'.$min.'" max="'.$max.'" step="'.$step.'" value="'.e($data[$name]??'').'"></label>';}
function editor_input(string $name,string $label,mixed $value,string $type='text'):void{echo '<label class="document-editor-field"><span>'.e($label).'</span><input name="'.e($name).'" type="'.e($type).'" value="'.e($value).'" required></label>';}
function editor_textarea(string $name,string $label,mixed $value):void{echo '<label class="document-editor-field"><span>'.e($label).'</span><textarea name="'.e($name).'" rows="3" required>'.e($value).'</textarea></label>';}
