<?php
declare(strict_types=1);

function e(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function tags(array $items): void { echo '<div class="flex flex-wrap gap-2">'; foreach ($items as $item) echo '<span class="tag">'.e($item).'</span>'; echo '</div>'; }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(ucfirst(str_replace('_',' ',$page)))?> — Portfolio</title><meta name="description" content="Developer portfolio, current systems, projects, activities, resume, and reflections."><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/style.css"></head><body class="bg-white text-black antialiased">
<aside class="sidebar no-print"><a href="/" class="sidebar-name"><?=e($profile['name']??'Cagatin Mark Jed')?></a><button id="menu-button" class="sidebar-menu-button">Menu</button><nav id="mobile-menu" class="sidebar-nav hidden"><?php foreach(['home'=>'Home','about'=>'About','projects'=>'Projects','activities'=>'Activities','reflections'=>'Reflections','resume'=>'Resume','contact'=>'Contact'] as $key=>$label):?><a href="<?=$key==='home'?'/':'/?page='.$key?>" class="<?=$page===$key?'active':''?>"><?=$label?></a><?php endforeach;?><?php if(owner_logged_in()):?><a href="/?page=admin">Edit portfolio</a><?php endif;?></nav></aside>
<main class="app-main">
<?php if($page==='home'):?>
<section class="hero-texture"><div class="site-width landing-profile py-20"><div class="profile-photo" role="img" aria-label="Profile photo placeholder"><span>CMJ</span></div><div class="profile-intro"><p class="label"><?=e($profile['role']??'Full-Stack Developer')?></p><h1 class="mt-4 text-5xl font-semibold tracking-[-.05em]"><?=e($profile['name']??'Cagatin Mark Jed')?></h1><p class="mt-5 max-w-xl text-lg text-neutral-600"><?=e($profile['intro']??'')?></p><p class="mt-3 max-w-xl text-neutral-600"><?=e($profile['biography']??'')?></p><div class="profile-meta"><span><?=e($profile['location']??'Metro Manila, Philippines')?></span><span><?=e($profile['availability']??'Open to collaborations')?></span></div><div class="mt-6"><?php tags($profile['skills']??[]);?></div><div class="mt-8 flex gap-3"><a class="button" href="/?page=projects">View projects</a><a class="button-outline" href="/?page=contact">Contact me</a></div></div><article class="current-work"><div class="section-heading"><span>01</span><p class="label">Currently building</p></div><div class="panel"><h2 class="text-2xl font-semibold tracking-tight"><?=e($system['name']??'Current system')?></h2><p class="mt-3 text-neutral-600"><?=e($system['summary']??'')?></p><div class="mt-6 flex justify-between text-sm"><span><?=e($system['status']??'')?></span><strong><?=e($system['progress']??0)?>%</strong></div><div class="mt-2 h-2 bg-neutral-200"><div class="h-full bg-neutral-700" style="width:<?=min(100,max(0,(int)($system['progress']??0)))?>%"></div></div><div class="mt-6"><?php tags($system['technologies']??[]);?></div></div></article></div></section>
<section class="site-width home-section py-20"><div class="section-heading"><span>02</span><p class="label">Selected work</p></div><div class="project-list"><?php foreach(array_slice($projects,0,3) as $index=>$item):$p=$item['data'];?><a class="project-row" href="/?page=project&slug=<?=e($item['slug'])?>"><span class="project-number"><?=str_pad((string)($index+1),2,'0',STR_PAD_LEFT)?></span><div><h3 class="text-2xl font-semibold"><?=e($p['title']??$item['title'])?></h3><p class="mt-2 text-neutral-600"><?=e($p['summary']??'')?></p></div><span class="project-arrow">↗</span></a><?php endforeach;?></div></section>
<?php elseif($page==='about'):?>
<?php page_head('About','Curious by nature. Deliberate in practice.',$profile['biography']??'');?><section class="site-width grid gap-10 py-16 md:grid-cols-[1fr_320px]"><div><h2 class="text-3xl font-semibold">Current system</h2><h3 class="mt-6 text-2xl"><?=e($system['name']??'')?></h3><p class="mt-3 text-neutral-600"><?=e($system['description']??'')?></p><p class="mt-6"><strong>Current focus:</strong> <?=e($system['current_focus']??'')?></p><p><strong>Next milestone:</strong> <?=e($system['next_milestone']??'')?></p></div><aside class="panel"><p class="label">Skills</p><div class="mt-5"><?php tags($profile['skills']??[]);?></div></aside></section>
<?php elseif(in_array($page,['projects','activities','reflections'],true)):?>
<?php page_head(ucfirst($page),$page==='projects'?'Systems shaped around real needs.':($page==='activities'?'Activities that sharpen the work.':'Experience, examined.'),'A clear record of the work, the process, and the lessons that followed.');?><section class="site-width grid gap-5 py-16 md:grid-cols-2"><?php foreach($items as $item):$d=$item['data'];$detail=$type==='project'?'project':($type==='activity'?'activity':'reflection');?><a class="panel" href="/?page=<?=$detail?>&slug=<?=e($item['slug'])?>"><p class="label"><?=e($d['date']??$d['year']??$d['category']??'')?></p><h2 class="mt-4 text-2xl font-semibold"><?=e($d['title']??$item['title'])?></h2><p class="mt-3 text-neutral-600"><?=e($d['summary']??$d['learning']??'')?></p><span class="mt-6 inline-block font-semibold">Read →</span></a><?php endforeach;?></section>
<?php elseif(in_array($page,['project','activity'],true)): if(!$item):http_response_code(404);echo '<div class="site-width py-20"><h1>Not found</h1></div>';else:$d=$item['data'];?>
<?php page_head(ucfirst($page),$d['title']??$item['title'],$d['summary']??'');?><article class="site-width max-w-3xl py-16"><p class="text-lg text-neutral-700"><?=nl2br(e($d['description']??''))?></p><?php $list=$d['highlights']??$d['outcomes']??[];if($list):?><h2 class="mt-10 text-2xl font-semibold">Highlights</h2><ul class="mt-4 list-disc space-y-2 pl-6"><?php foreach($list as $line):?><li><?=e($line)?></li><?php endforeach;?></ul><?php endif;?></article><?php endif;?>
<?php elseif($page==='resume'): $d=$item['data']??[];?>
<section class="site-width py-10"><div class="no-print mb-5 flex items-center justify-between"><div><p class="label">A4 document</p><h1 class="mt-2 text-3xl font-semibold">Resume</h1></div><button onclick="window.print()" class="button">Print / Save PDF</button></div><div class="paper-shell"><article class="paper <?=e($layout['resume_template'])?>" style="--doc-size:<?=e($layout['font_size'])?>pt;--doc-line:<?=e($layout['line_height'])?>;--doc-space:<?=e($layout['section_spacing'])?>px;font-family:<?=e($layout['font_family'])?>,Arial,sans-serif"><header class="text-center border-b-2 border-black pb-4"><h1 class="text-4xl font-bold"><?=e($d['name']??'')?></h1><p class="font-semibold"><?=e($d['headline']??'')?></p><p class="text-sm text-neutral-600"><?=e(($d['email']??'').' · '.($d['phone']??'').' · '.($d['location']??''))?></p></header><?php doc_section('Summary','<p>'.e($d['summary']??'').'</p>');doc_entries('Experience',$d['experience']??[],'role','organization');doc_entries('Education',$d['education']??[],'degree','school');?><section class="doc-section"><h2>Skills</h2><?php foreach($d['skills']??[] as $s):?><p><strong><?=e($s['group']??'')?>:</strong> <?=e(implode(' · ',$s['items']??[]))?></p><?php endforeach;?></section></article></div></section>
<?php elseif($page==='reflection'): if(!$item):http_response_code(404);echo 'Not found';else:$d=$item['data']?>
<section class="site-width py-10"><div class="no-print mb-5 flex items-center justify-between"><h1 class="text-3xl font-semibold"><?=e($d['title'])?></h1><button onclick="window.print()" class="button">Print / Save PDF</button></div><div class="paper-shell"><article class="paper reflection" style="--doc-size:<?=e($layout['font_size'])?>pt;--doc-line:<?=e($layout['line_height'])?>;--doc-space:<?=e($layout['section_spacing'])?>px;font-family:<?=e($layout['font_family'])?>,Arial,sans-serif"><header class="pb-8 text-center"><p class="label">Reflection paper</p><h1 class="mt-4 text-4xl font-bold"><?=e($d['title'])?></h1><p><?=e($d['activity']??'')?></p></header><div class="grid grid-cols-2 gap-2 bg-neutral-100 p-4 text-sm"><p><strong>Date:</strong> <?=e($d['date']??'')?></p><p><strong>Course:</strong> <?=e($d['course']??'')?></p><p><strong>Instructor:</strong> <?=e($d['instructor']??'')?></p><p><strong>Author:</strong> Cagatin Mark Jed</p></div><?php foreach(['Experience'=>'experience','Observations'=>'observations','Learning'=>'learning','Next Steps'=>'next_steps','Conclusion'=>'conclusion'] as $label=>$key)doc_section($label,'<p>'.e($d[$key]??'').'</p>');?></article></div></section><?php endif;?>
<?php elseif($page==='contact'):?><?php page_head('Contact','Let’s build something useful.',$contact['message']??'');?><section class="site-width grid gap-5 py-16 md:grid-cols-2"><a class="panel" href="mailto:<?=e($contact['email']??'')?>"><p class="label">Email</p><h2 class="mt-4 text-2xl font-semibold"><?=e($contact['email']??'')?></h2></a><div class="panel"><p class="label">Links</p><?php foreach($contact['links']??[] as $link):?><a class="mt-4 block font-semibold" target="_blank" rel="noreferrer" href="<?=e($link['url'])?>"><?=e($link['label'])?> ↗</a><?php endforeach;?></div></section>
<?php elseif($page==='login'):?><section class="site-width flex min-h-[70vh] items-center justify-center py-16"><form method="post" class="panel w-full max-w-md"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="login"><p class="label">Owner access</p><h1 class="mt-4 text-3xl font-semibold">Sign in</h1><?php if($error):?><p class="mt-4 border border-neutral-400 bg-neutral-100 p-3"><?=e($error)?></p><?php endif;?><label class="mt-6 block text-sm font-semibold">Email<input class="field" name="email" type="email" required></label><label class="mt-4 block text-sm font-semibold">Password<input class="field" name="password" type="password" required></label><button class="button mt-6 w-full">Sign in</button></form></section>
<?php elseif($page==='admin'):require_owner();?><?php page_head('Admin','Portfolio content','Edit drafts and publish only when the content is ready.');?><section class="site-width py-12"><div class="mb-6 flex flex-wrap gap-3"><a class="button-outline" href="/?page=layouts">Paper templates</a><?php foreach(['project','activity','reflection'] as $newType):?><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="create"><input type="hidden" name="type" value="<?=$newType?>"><button class="button-outline">New <?=$newType?></button></form><?php endforeach;?><form method="post"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="logout"><button class="button-outline">Sign out</button></form></div><div class="space-y-3"><?php foreach($items as $item):?><div class="panel flex items-center justify-between gap-4"><div><p class="label"><?=e($item['type'])?> · <?=$item['is_published']?'Published':'Draft'?></p><h2 class="mt-2 text-xl font-semibold"><?=e($item['title'])?></h2></div><a class="button-outline" href="/?page=edit&id=<?=e($item['id'])?>">Edit</a></div><?php endforeach;?></div></section>
<?php elseif($page==='edit'):require_owner();if(!$item):echo 'Not found';else:?><section class="site-width max-w-3xl py-12"><a href="/?page=admin">← Admin</a><h1 class="mt-5 text-3xl font-semibold">Edit <?=e($item['title'])?></h1><?php if($error):?><p class="mt-4 bg-neutral-100 p-3"><?=e($error)?></p><?php endif;?><form method="post" class="mt-8 space-y-5"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="id" value="<?=e($item['id'])?>"><label class="block font-semibold">Title<input class="field" name="title" value="<?=e($item['title'])?>" required></label><label class="block font-semibold">URL slug<input class="field" name="slug" value="<?=e($item['slug'])?>" pattern="[a-z0-9-]+" required></label><label class="block font-semibold">Display order<input class="field" name="sort_order" type="number" value="<?=e($item['sort_order'])?>"></label><label class="block font-semibold">Content data<textarea class="field min-h-96 font-mono text-sm" name="data" required><?=e(json_encode($item['data'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></textarea><span class="mt-1 block text-sm font-normal text-neutral-500">Edit values inside the JSON. Keep property names and punctuation unchanged.</span></label><div class="flex flex-wrap gap-2"><button class="button-outline" name="action" value="save">Save draft</button><button class="button" name="action" value="publish">Save & publish</button><?php if($item['is_published']):?><button class="button-outline" name="action" value="unpublish">Unpublish</button><?php endif;?><?php if(in_array($item['type'],['project','activity','reflection'],true)):?><button class="button-outline" onclick="return confirm('Delete this item?')" name="action" value="delete">Delete</button><?php endif;?></div></form></section><?php endif;?>
<?php elseif($page==='layouts'):require_owner()?><section class="site-width max-w-3xl py-12"><p class="label">Paper templates only</p><h1 class="mt-4 text-4xl font-semibold">Resume and reflection layout</h1><p class="mt-3 text-neutral-600">A4 size and one-inch margins are fixed and apply only to printed documents.</p><form method="post" class="panel mt-8 grid gap-5 md:grid-cols-2"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="layout"><?php select_field('resume_template','Resume template',['classic'=>'Classic','modern'=>'Modern'],$layout);select_field('reflection_template','Reflection template',['academic'=>'Academic','journal'=>'Journal'],$layout);select_field('font_family','Font',['Arial'=>'Arial','Georgia'=>'Georgia','Inter'=>'Inter'],$layout);number_field('font_size','Font size',8,14,.5,$layout);number_field('line_height','Line height',1.1,2,.05,$layout);number_field('section_spacing','Section spacing',8,32,1,$layout);?><button class="button md:col-span-2">Save layout</button></form></section>
<?php else:http_response_code(404);?><section class="site-width py-24"><h1 class="text-5xl font-semibold">Page not found</h1></section><?php endif;?>
</main><footer class="app-footer no-print border-t border-neutral-200"><div class="site-width flex justify-between py-7 text-sm text-neutral-500"><span>© <?=date('Y')?> <?=e($profile['name']??'Portfolio')?></span><a href="/?page=login">Owner</a></div></footer><script src="/assets/app.js"></script></body></html>
<?php
function page_head(string $label,string $title,string $description):void{echo '<header class="border-b border-neutral-200"><div class="site-width py-16"><p class="label">'.e($label).'</p><h1 class="mt-4 text-5xl font-semibold tracking-[-.04em]">'.e($title).'</h1><p class="mt-5 max-w-3xl text-lg text-neutral-600">'.e($description).'</p></div></header>';}
function doc_section(string $title,string $html):void{echo '<section class="doc-section"><h2>'.e($title).'</h2>'.$html.'</section>';}
function doc_entries(string $title,array $entries,string $primary,string $secondary):void{ob_start();foreach($entries as $entry){echo '<article class="mb-3 break-inside-avoid"><div class="flex justify-between gap-4"><strong>'.e($entry[$primary]??'').' · '.e($entry[$secondary]??'').'</strong><span>'.e($entry['period']??'').'</span></div>';if(isset($entry['details'])&&is_array($entry['details'])){echo '<ul class="list-disc pl-5">';foreach($entry['details'] as $x)echo '<li>'.e($x).'</li>';echo '</ul>';}elseif(isset($entry['details']))echo '<p>'.e($entry['details']).'</p>';echo '</article>';}doc_section($title,ob_get_clean());}
function select_field(string $name,string $label,array $choices,array $data):void{echo '<label class="font-semibold">'.e($label).'<select class="field" name="'.e($name).'">';foreach($choices as $value=>$text)echo '<option value="'.e($value).'" '.(($data[$name]??'')===$value?'selected':'').'>'.e($text).'</option>';echo '</select></label>';}
function number_field(string $name,string $label,float $min,float $max,float $step,array $data):void{echo '<label class="font-semibold">'.e($label).'<input class="field" type="number" name="'.e($name).'" min="'.$min.'" max="'.$max.'" step="'.$step.'" value="'.e($data[$name]??'').'"></label>';}
